- frontend/src/app/features/cart/cart-item/cart-item.component.css
- frontend/src/app/features/cart/cart-item/cart-item.component.html
- frontend/src/app/features/cart/cart-item/cart-item.component.ts
- frontend/src/app/features/cart/cart.component.html
- frontend/src/app/features/cart/cart.component.ts
- frontend/src/app/model/interfaces/address.interface.ts
- frontend/src/app/model/interfaces/cart-item.interface.ts
- frontend/src/app/model/interfaces/order.interface.ts
- frontend/src/app/model/interfaces/product.interface.ts
- frontend/src/app/model/interfaces/shopping-cart.interface.ts
- frontend/src/app/model/interfaces/user-data.interface.ts
- All of the products in the cart will be shown by cart-item component #9 
- Update quantity and cancel product functionalities are yet to be implemented
- Implement model classes using interface for easy accessibility in data
> [New Feature] Implement cart item view

- backend/.env.example
- backend/.gitignore
- backend/BACKEND_README.md
- backend/Dockerfile
- backend/HELP.md
- backend/docker-compose.yml
- backend/mvnw
- backend/mvnw.cmd
- backend/pom.xml
- backend/src/main/java/com/cloud/webshop/WebshopApplication.java
- backend/src/main/java/com/cloud/webshop/config/SecurityConfig.java
- backend/src/main/java/com/cloud/webshop/config/SwaggerConfig.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/cloud/webshop/WebshopApplicationTests.java
- backend/target/classes/application.yml
- database/Dockerfile
- Create the backend project
- Project dockerization
- Install necessary libraries
- Implement swagger UI for the API documentation
- Project Running Documentation
- Setup database with docker
- Connect the database to the backend
> Backend and db

- backend/src/main/java/com/cloud/webshop/config/SecurityConfig.java
- backend/src/main/java/com/cloud/webshop/controller/ProductController.java
- backend/src/main/java/com/cloud/webshop/model/Product.java
- backend/src/main/java/com/cloud/webshop/repository/ProductRepository.java
- backend/src/main/java/com/cloud/webshop/response/ApiResponse.java
- backend/src/main/java/com/cloud/webshop/response/ProductResponse.java
- backend/src/main/java/com/cloud/webshop/service/ProductService.java
- backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
- Implemented product list API
- Implemented pagination
- Created Product Model
- Created Repository, Service, and Implementation files
- Created Responses
> Implemented product list api

- frontend/src/app/features/products/product-detail/product-detail.component.css
- frontend/src/app/features/products/product-detail/product-detail.component.html
- frontend/src/app/features/products/product-detail/product-detail.component.ts
Created product-detail with css changes
> product-detail created

- frontend/src/app/features/products/product-detail/product-detail.component.css
- frontend/src/app/features/products/product-detail/product-detail.component.html
- frontend/src/app/features/products/product-detail/product-detail.component.ts
frontend product details page added
> product-detail added

- backend/.dockerignore
- backend/Dockerfile
- backend/docker-compose.yml
- backend/src/main/java/com/cloud/webshop/WebshopApplication.java
- backend/src/main/java/com/cloud/webshop/config/DotenvInitializer.java
- backend/src/main/java/com/cloud/webshop/controller/ProductController.java
- backend/src/main/resources/application.yml
- backend/target/classes/application.yml
- Optimized dockerfile
- .env file loader added so that the backend can be run from the intellij idea
- cors issue solved
> dockerfile optimized, .env loader added for running locally. Ref #18

- backend/src/main/java/com/cloud/webshop/model/INVENTORY.java
- backend/src/main/java/com/cloud/webshop/model/ORDER.java
- backend/src/main/java/com/cloud/webshop/model/ORDER_PRODUCT.java
- backend/src/main/java/com/cloud/webshop/model/Product.java
- backend/src/main/java/com/cloud/webshop/model/SUPPLIER.java
ORDER file added
Product file modified
> Product file modified

- backend/src/main/java/com/cloud/webshop/controller/ProductController.java
- backend/src/main/java/com/cloud/webshop/service/ProductService.java
- backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
- service function added for product by id
- implementation function added for product by id
- Api implemented for product by id
> Product by id api with service implementation and repository implemented

- backend/src/main/java/com/cloud/webshop/config/WebConfig.java
- Allow requests from all origins #41
> [Backend] Add CORS configuration for API endpoints

- frontend/src/app/app.routes.ts
- frontend/src/app/features/products/handle-product/handle-product.component.ts
- frontend/src/app/features/products/product-add/add-product.component.css
- frontend/src/app/features/products/product-add/add-product.component.html
- frontend/src/app/features/products/product-add/add-product.component.ts
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
- frontend/src/app/shared/utils/lazy-loading.utils.ts
> [UI] Add new product page

- frontend/src/app/features/cart/cart-item/cart-item.component.html
- frontend/src/app/features/cart/cart-item/cart-item.component.ts
- frontend/src/app/features/cart/cart.component.ts
- frontend/src/app/features/products/product-detail/product-detail.component.ts
- frontend/src/app/model/interfaces/base-response.interface.ts
- frontend/src/app/model/interfaces/cart-item.interface.ts
- frontend/src/app/model/interfaces/shopping-cart.interface.ts
- frontend/src/app/services/app-state.service.ts
- frontend/src/app/services/cart.service.ts
- frontend/src/app/services/rest.service.ts
> [UI] Implemented cart-list and integrated with backend #43

- frontend/src/app/features/products/product-add/add-product.component.html
- frontend/src/app/features/products/product-add/add-product.component.ts
- frontend/src/app/features/products/product-detail/product-detail.component.css
- frontend/src/app/features/products/product-detail/product-detail.component.html
- frontend/src/app/features/products/product-detail/product-detail.component.ts
> [UI] Implemented product update page

- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.css
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.ts
- Add Manage Inventory item #51 
- Add sub items under Manage Inventory
- Make responsive for both desktop and mobile
> [UI] Add Manage Inventory item in the nav bar

- frontend/src/app/features/products/product-list/product-list.component.css
- frontend/src/app/features/products/product-list/product-list.component.html
- frontend/src/app/features/products/product-list/product-list.component.ts
- frontend/src/app/services/guard.service.ts
- frontend/src/app/services/rest.service.ts
- frontend/src/index.html
> [UI] implemented search functionality in product list

- frontend/src/app/app.routes.ts
- frontend/src/app/enum/route.enum.ts
- frontend/src/app/features/supplier/supplier-add/add-supplier.component.css
- frontend/src/app/features/supplier/supplier-add/add-supplier.component.html
- frontend/src/app/features/supplier/supplier-add/add-supplier.component.ts
- frontend/src/app/model/interfaces/supplier.interface.ts
- frontend/src/app/services/supplier.service.ts
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
- frontend/src/app/shared/utils/lazy-loading.utils.ts
> [UI] Implement add supplier page with network call

- backend/src/main/java/com/cloud/webshop/controller/ProductController.java
- backend/src/main/java/com/cloud/webshop/response/ProductNameResponse.java
- backend/src/main/java/com/cloud/webshop/response/ProductResponse.java
- backend/src/main/java/com/cloud/webshop/service/ProductService.java
- backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
1. Product List with id and name
2. Product list without inventory check
3. Product list with a search parameter of isAvailable(default value is false, if it is set to true, you'll get only products which have quantity>0)
4. Inventory id provided with product list API
> Modify product list with custom search, individual product list API

- frontend/src/app/features/orders/manage-order/manage-orders.component.css
- frontend/src/app/features/orders/manage-order/manage-orders.component.html
- frontend/src/app/features/orders/manage-order/manage-orders.component.ts
- frontend/src/app/model/interfaces/order.interface.ts
- frontend/src/app/services/order.service.ts
> [UI] Show order history in ui

- frontend/angular.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/features/inventory/add-inventory/add-inventory.component.css
- frontend/src/app/features/inventory/add-inventory/add-inventory.component.html
- frontend/src/app/features/inventory/add-inventory/add-inventory.component.ts
- frontend/src/app/features/products/product-detail/product-detail.component.css
- frontend/src/app/features/products/product-detail/product-detail.component.html
- frontend/src/app/features/products/product-detail/product-detail.component.ts
- frontend/src/app/features/products/product-list/product-list.component.ts
- frontend/src/app/model/interfaces/inventory.interface.ts
- frontend/src/app/model/interfaces/product.interface.ts
- frontend/src/app/model/product.model.ts
- frontend/src/app/services/guard.service.ts
- frontend/src/app/services/inventory.service.ts
- frontend/src/app/services/rest.service.ts
- frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.ts
- frontend/src/index.html
- frontend/src/main.ts
- frontend/src/styles.css
> [UI] Implemented update and delete inventory functionality

- frontend/.dockerignore
- frontend/Dockerfile
- frontend/nginx.conf
- frontend/src/app/features/products/product-add/add-product.component.html
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
> Dockerise the Frontend

- frontend/src/app/features/cart/cart-item/cart-item.component.ts
- frontend/src/app/features/cart/cart.component.html
- frontend/src/app/features/cart/cart.component.ts
- frontend/src/app/model/interfaces/cart-item.interface.ts
- frontend/src/app/services/rest.service.ts
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.css
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
- frontend/src/app/shared/components/header/navigation-items/navigation-items.component.ts
- frontend/src/environments/environment.ts
> Add the cart count in navbar  and integrate delete api in cart item

- frontend/src/app/features/cart/cart.component.css
- frontend/src/app/features/cart/cart.component.html
- frontend/src/app/features/orders/manage-order/manage-orders.component.css
- frontend/src/app/features/orders/manage-order/manage-orders.component.html
- frontend/src/app/features/products/product-detail/product-detail.component.css
- frontend/src/app/features/products/product-detail/product-detail.component.html
- frontend/src/app/shared/components/header/header.component.css
- frontend/src/app/shared/components/icons/back-arrow-icon/back-arrow-icon.component.ts
> Fix some known issues with proper validation

- frontend/src/app/features/products/product-list/product-list.component.ts
- frontend/src/app/services/guard.service.ts
> price range filter in product list

- backend/src/main/java/com/cloud/webshop/WebshopApplication.java
- backend/src/main/java/com/cloud/webshop/repository/InventoryRepository.java
- backend/src/main/java/com/cloud/webshop/service/InventoryMonitoringService.java
- backend/src/main/resources/templates/low-stock-alert.html
> [Backend] Implement low stock warning mail
